package llm

import "context"

// CompletionRequest is an input for LLM generation. It contains the system prompt, user prompt, and generation parameters like temperature.
type CompletionRequest struct {
	SystemPrompt string
	UserPrompt   string
	Temperature  float64
}

// CompletionResponse is the output from non-streaming LLM generation.
type CompletionResponse struct {
	Content string
}

// StreamChunk is a chunk of token generated by streaming LLM generation. It contains the content of the chunk and a flag indicating if it's the last chunk.
type StreamChunk struct {
	Content string
	Done    bool
}

// LLM is an interface for all language model providers. It defines methods for generating text completions, both in streaming and non-streaming ways.
type LLM interface {
	// Generate produces a whole completion (non-streaming)
	Generate(ctx context.Context, req CompletionRequest) (*CompletionResponse, error)

	// GenerateStream produces a completion in a streaming way.
	// Token chunks are sent one by one through channel chunks.
	// Caller is responsible for draining the channel until it's closed.
	GenerateStream(ctx context.Context, req CompletionRequest, chunks chan<- StreamChunk) error
}
